# Site settings
title: 漫画萌 - 轻博客
tagline: 轻量级漫画萌资讯博客
description: > # this means to ignore newlines until "baseurl:"
  这是关于漫画萌的一个轻量级博客，为大家简单的介绍一下漫画萌咩~.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.comicmoe.net" # the base hostname & protocol for your site

# Plugins
gems: ["jekyll-paginate"]

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Pagination
paginate: 4
paginate_path: "/blog/page:num/"